import Navbar from "@/components/Navbar";
import "../styles/globals.css";
import "../styles/normalize.css";
import { AuthProvider } from "@/context/AuthContext";

export const metadata = {
  title: "Name",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <Navbar />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
