import "../styles/globals.css";
import "../styles/normalize.css";

export const metadata = {
  title: "Name",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
